name: Tag version (playground)
on:
  push:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: |
          VERSION=$(cat ./version)
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.RELEASE_VERSION }}
          create_annotated_tag: true
          tag_prefix: v

      - name: Fail if version tag was not pushed
        if: ${{ steps.tag_version.outputs.new_tag }} == undefined
        run: exit 1
